Repository tobiasehlert/teslamateapi, pull requests merged in 2021-03, with the labels that each got.

#9 proxy commands to Tesla API
  src/v1_TeslaMateAPICarsCommand.go
  src/webserver.go
Labels: enhancement, go

#15 add random string to mqtt clientID to prevent concurrent connections
  src/v1_TeslaMateAPICarsStatus.go
Labels: bug, go

#16 defer disconnection to prevent un-managed disconnects
  src/v1_TeslaMateAPICarsStatus.go
Labels: bug, go

#17 adding mqtt sleep time before doing disconnect
  README.md
  src/v1_TeslaMateAPICarsStatus.go
Labels: documentation, enhancement, go

#21 Refactor MQTT so it connects once to broker and caches messages
  src/v1_TeslaMateAPICarsStatus.go
  src/webserver.go
Labels: go

#22 Feature commands to proxy POST commands to Tesla owner API
  README.md
  example/allow_list.json
  src/AuthSupport.go
  src/CommandSupport.go
  src/v1_TeslaMateAPICarsCommand.go
  src/webserver.go
Labels: documentation, enhancement, go
