Repository tobiasehlert/teslamateapi, pull requests merged in 2021-05, with the labels that each got.

#34 add support for teslamate logging resume/suspend
  README.md
  src/CommandSupport.go
  src/v1_TeslaMateAPICarsLoggingCommand.go
  src/webserver.go
Labels: documentation, enhancement, go

#37 Convert SpeedMax and SpeedAvg in Drive (km->mi)
  src/v1_TeslaMateAPICarsDrives.go
Labels: bug, go, good first issue, solved

#42 Adding persistant MQTT connection for status endpoint
  CHANGELOG.md
  README.md
  go.mod
  go.sum
  src/v1_TeslaMateAPICarsStatus.go
  src/webserver.go
Labels: dependencies, enhancement, go

#39 Patch 2
  src/v1_TeslaMateAPICarsChargesDetails.go
Labels: bug, go

#60 Feature 10 logging commands
  README.md
  src/CommandSupport.go
  src/v1_TeslaMateAPICarsLogging.go
  src/webserver.go
Labels: documentation, enhancement, go
