Repository tobiasehlert/teslamateapi, pull requests merged in 2025-09, with the labels that each got.

#354 fix(docker): adjust chmod permissions on binary
  Dockerfile
Labels: bug, good first issue, docker

#348 fix: Postgres SSL connection
  README.md
  src/webserver.go
Labels: bug, documentation, good first issue, go

#362 feat(ci): use multiple runners for build
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement, github_actions

#363 fix(ci): use dockerhub variable instead
  .github/workflows/build.yml
Labels: github_actions

#349 feat: add energy consumption to drives and drive details
  src/v1_TeslaMateAPICarsDrives.go
  src/v1_TeslaMateAPICarsDrivesDetails.go
Labels: enhancement, go

#366 fix: incorrect 0 values from charge_energy_used charges queries
  src/v1_TeslaMateAPICarsCharges.go
  src/v1_TeslaMateAPICarsChargesDetails.go
Labels: go

#367 chore: rewrite logic of convertStringTo-functions
  src/webserver.go
Labels: go
